/*
 * This file is part of LiquidBounce (https://github.com/CCBlueX/LiquidBounce)
 *
 * Copyright (c) 2015 - 2025 CCBlueX
 *
 * LiquidBounce is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LiquidBounce is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LiquidBounce. If not, see <https://www.gnu.org/licenses/>.
 */

package net.ccbluex.liquidbounce.ksp

import com.google.devtools.ksp.isPublic
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import net.ccbluex.liquidbounce.annotations.InbuiltModule

class ClientModuleProcessor(private val environment: SymbolProcessorEnvironment) : SymbolProcessor {

    lateinit var modules: Sequence<KSClassDeclaration>

    override fun process(resolver: Resolver): List<KSAnnotated> {
        // val clientModules = resolver.getSymbolsWithAnnotation(ClientModule::class).toList()

        modules = resolver.getSymbolsWithAnnotation(InbuiltModule::class.qualifiedName!!)
            .filterIsInstance<KSClassDeclaration>()
            .filter {
                // @InbuiltModule object XXX : ClientModule(...)
                it.classKind == ClassKind.OBJECT && it.isPublic()
            }
        return emptyList()
    }

    override fun finish() {
        environment.codeGenerator.createNewFile(
            dependencies = Dependencies.ALL_FILES,
            packageName = "net.ccbluex.liquidbounce.features.module",
            fileName = "ClientModules",
        ).bufferedWriter().use { writer ->
            writer
                .appendLine("// This file is generated by the KSP module.")
                .appendLine("@file:JvmName(\"-ClientModules\")") // hide to Java
                .appendLine("package net.ccbluex.liquidbounce.features.module")
                .appendLine() // imports
                .appendLine("import java.util.Arrays")
                .appendLine("import java.util.Collections")
                .appendLine("import net.ccbluex.liquidbounce.LiquidBounce")
                .appendLine("import net.ccbluex.liquidbounce.features.module.ClientModule")
                .appendLine() // list
                .appendLine("private val clientModules: List<ClientModule> = Collections.unmodifiableList(Arrays.asList(")
                .apply {
                    modules.forEach { module ->
                        writer.appendLine("    ${module.qualifiedName!!.asString()},")
                    }
                }
                .appendLine("))")
                .appendLine()
                .appendLine(
                    "internal inline val LiquidBounce.allClientModules: List<ClientModule> get() = clientModules"
                )
        }
    }

}
