/*
 * LiquidBounce Hacked Client
 * A free open source mixin-based injection hacked client for Minecraft using Minecraft Forge.
 * https://github.com/CCBlueX/LiquidBounce/
 */

package net.ccbluex.liquidbounce.api.enums

enum class BlockType {
    ENCHANTING_TABLE,
    CHEST,
    ENDER_CHEST,
    TRAPPED_CHEST,
    ANVIL,
    SAND,
    WEB,
    TORCH,
    CRAFTING_TABLE,
    FURNACE,
    WATERLILY,
    DISPENSER,
    STONE_PRESSURE_PLATE,
    WODDEN_PRESSURE_PLATE,
    TNT,
    STANDING_BANNER,
    WALL_BANNER,
    REDSTONE_TORCH,
    NOTEBLOCK,
    DROPPER,
    SNOW_LAYER,
    AIR,
    ICE_PACKED,
    ICE,
    WATER,
    BARRIER,
    FLOWING_WATER,
    COAL_ORE,
    IRON_ORE,
    GOLD_ORE,
    REDSTONE_ORE,
    LAPIS_ORE,
    DIAMOND_ORE,
    EMERALD_ORE,
    QUARTZ_ORE,
    CLAY,
    GLOWSTONE,
    LADDER,
    COAL_BLOCK,
    IRON_BLOCK,
    GOLD_BLOCK,
    DIAMOND_BLOCK,
    EMERALD_BLOCK,
    REDSTONE_BLOCK,
    LAPIS_BLOCK,
    FIRE,
    MOSSY_COBBLESTONE,
    MOB_SPAWNER,
    END_PORTAL_FRAME,
    BOOKSHELF,
    COMMAND_BLOCK,
    LAVA,
    FLOWING_LAVA,
    LIT_FURNACE,
    DRAGON_EGG,
    BROWN_MUSHROOM_BLOCK,
    RED_MUSHROOM_BLOCK,
    FARMLAND
}