#
# ⠞⠓⠊⠎ ⠋⠊⠇⠑ ⠊⠎ ⠏⠁⠗⠞ ⠕⠋ ⠇⠊⠟⠥⠊⠙⠃⠕⠥⠝⠉⠑ (⠓⠞⠞⠏⠎://⠛⠊⠞⠓⠥⠃.⠉⠕⠍/⠉⠉⠃⠇⠥⠑⠭/⠇⠊⠟⠥⠊⠙⠃⠕⠥⠝⠉⠑)
#
# ⠉⠕⠏⠽⠗⠊⠛⠓⠞ (⠉) 2015 - 2025 ⠉⠉⠃⠇⠥⠑⠭
#
# ⠇⠊⠟⠥⠊⠙⠃⠕⠥⠝⠉⠑ ⠊⠎ ⠋⠗⠑⠑ ⠎⠕⠋⠞⠺⠁⠗⠑: ⠽⠕⠥ ⠉⠁⠝ ⠗⠑⠙⠊⠎⠞⠗⠊⠃⠥⠞⠑ ⠊⠞ ⠁⠝⠙/⠕⠗ ⠍⠕⠙⠊⠋⠽
# ⠊⠞ ⠥⠝⠙⠑⠗ ⠞⠓⠑ ⠞⠑⠗⠍⠎ ⠕⠋ ⠞⠓⠑ ⠛⠝⠥ ⠛⠑⠝⠑⠗⠁⠇ ⠏⠥⠃⠇⠊⠉ ⠇⠊⠉⠑⠝⠎⠑ ⠁⠎ ⠏⠥⠃⠇⠊⠎⠓⠑⠙ ⠃⠽
# ⠞⠓⠑ ⠋⠗⠑⠑ ⠎⠕⠋⠞⠺⠁⠗⠑ ⠋⠕⠥⠝⠙⠁⠞⠊⠕⠝, ⠑⠊⠞⠓⠑⠗ ⠧⠑⠗⠎⠊⠕⠝ 3 ⠕⠋ ⠞⠓⠑ ⠇⠊⠉⠑⠝⠎⠑, ⠕⠗
# (⠁⠞ ⠽⠕⠥⠗ ⠕⠏⠞⠊⠕⠝) ⠁⠝⠽ ⠇⠁⠞⠑⠗ ⠧⠑⠗⠎⠊⠕⠝.
#
# ⠇⠊⠟⠥⠊⠙⠃⠕⠥⠝⠉⠑ ⠊⠎ ⠙⠊⠎⠞⠗⠊⠃⠥⠞⠑⠙ ⠊⠝ ⠞⠓⠑ ⠓⠕⠏⠑ ⠞⠓⠁⠞ ⠊⠞ ⠺⠊⠇⠇ ⠃⠑ ⠥⠎⠑⠋⠥⠇,
# ⠃⠥⠞ ⠺⠊⠞⠓⠕⠥⠞ ⠁⠝⠽ ⠺⠁⠗⠗⠁⠝⠞⠽; ⠺⠊⠞⠓⠕⠥⠞ ⠑⠧⠑⠝ ⠞⠓⠑ ⠊⠍⠏⠇⠊⠑⠙ ⠺⠁⠗⠗⠁⠝⠞⠽ ⠕⠋
# ⠍⠑⠗⠉⠓⠁⠝⠞⠁⠃⠊⠇⠊⠞⠽ ⠕⠗ ⠋⠊⠞⠝⠑⠎⠎ ⠋⠕⠗ ⠁ ⠏⠁⠗⠞⠊⠉⠥⠇⠁⠗ ⠏⠥⠗⠏⠕⠎⠑. ⠎⠑⠑ ⠞⠓⠑
# ⠛⠝⠥ ⠛⠑⠝⠑⠗⠁⠇ ⠏⠥⠃⠇⠊⠉ ⠇⠊⠉⠑⠝⠎⠑ ⠋⠕⠗ ⠍⠕⠗⠑ ⠙⠑⠞⠁⠊⠇⠎.
#
# ⠽⠕⠥ ⠎⠓⠕⠥⠇⠙ ⠓⠁⠧⠑ ⠗⠑⠉⠑⠊⠧⠑⠙ ⠁ ⠉⠕⠏⠽ ⠕⠋ ⠞⠓⠑ ⠛⠝⠥ ⠛⠑⠝⠑⠗⠁⠇ ⠏⠥⠃⠇⠊⠉ ⠇⠊⠉⠑⠝⠎⠑
# ⠁⠇⠕⠝⠛ ⠺⠊⠞⠓ ⠇⠊⠟⠥⠊⠙⠃⠕⠥⠝⠉⠑. ⠊⠋ ⠝⠕⠞, ⠎⠑⠑ <⠓⠞⠞⠏⠎://⠺⠺⠺.⠛⠝⠥.⠕⠗⠛/⠇⠊⠉⠑⠝⠎⠑⠎/>.
#
⠅⠕⠞⠇⠊⠝.⠉⠕⠙⠑.⠎⠞⠽⠇⠑=⠕⠋⠋⠊⠉⠊⠁⠇
⠅⠕⠞⠇⠊⠝.⠊⠝⠉⠗⠑⠍⠑⠝⠞⠁⠇=⠞⠗⠥⠑
⠅⠕⠞⠇⠊⠝.⠉⠁⠉⠓⠊⠝⠛.⠑⠝⠁⠃⠇⠑⠙=⠞⠗⠥⠑
⠅⠕⠞⠇⠊⠝.⠏⠁⠗⠁⠇⠇⠑⠇.⠞⠁⠎⠅⠎.⠊⠝.⠏⠗⠕⠚⠑⠉⠞=⠞⠗⠥⠑

# ⠛⠗⠁⠙⠇⠑ ⠎⠑⠞⠞⠊⠝⠛⠎
⠕⠗⠛.⠛⠗⠁⠙⠇⠑.⠙⠁⠑⠍⠕⠝=⠞⠗⠥⠑
⠕⠗⠛.⠛⠗⠁⠙⠇⠑.⠏⠁⠗⠁⠇⠇⠑⠇=⠞⠗⠥⠑
⠕⠗⠛.⠛⠗⠁⠙⠇⠑.⠉⠁⠉⠓⠊⠝⠛=⠞⠗⠥⠑
#⠕⠗⠛.⠛⠗⠁⠙⠇⠑.⠉⠕⠝⠋⠊⠛⠥⠗⠁⠞⠊⠕⠝-⠉⠁⠉⠓⠑=⠞⠗⠥⠑
# ⠵⠛⠉ ⠋⠗⠕⠍ ⠚⠙⠅ 21
⠕⠗⠛.⠛⠗⠁⠙⠇⠑.⠚⠧⠍⠁⠗⠛⠎=-⠭⠍⠎1024⠍ -⠭⠍⠭4096⠍ -⠭⠭:+⠥⠎⠑⠵⠛⠉

# ⠋⠁⠃⠗⠊⠉ ⠏⠗⠕⠏⠑⠗⠞⠊⠑⠎
# ⠉⠓⠑⠉⠅ ⠞⠓⠑⠎⠑ ⠕⠝ ⠓⠞⠞⠏⠎://⠋⠁⠃⠗⠊⠉⠍⠉.⠝⠑⠞/⠧⠑⠗⠎⠊⠕⠝⠎.⠓⠞⠍⠇
⠍⠊⠝⠑⠉⠗⠁⠋⠞_⠧⠑⠗⠎⠊⠕⠝=1.21.4
⠽⠁⠗⠝_⠍⠁⠏⠏⠊⠝⠛⠎=1.21.4+⠃⠥⠊⠇⠙.8
⠇⠕⠁⠙⠑⠗_⠧⠑⠗⠎⠊⠕⠝=0.16.10
⠍⠊⠝_⠇⠕⠁⠙⠑⠗_⠧⠑⠗⠎⠊⠕⠝=0.16.5

# ⠋⠁⠃⠗⠊⠉ ⠁⠏⠊
⠋⠁⠃⠗⠊⠉_⠧⠑⠗⠎⠊⠕⠝=0.118.0+1.21.4
# ⠇⠕⠕⠍
⠇⠕⠕⠍_⠧⠑⠗⠎⠊⠕⠝=1.9-⠎⠝⠁⠏⠎⠓⠕⠞
# ⠍⠕⠙ ⠏⠗⠕⠏⠑⠗⠞⠊⠑⠎
⠍⠕⠙_⠧⠑⠗⠎⠊⠕⠝=0.30.1
⠍⠁⠧⠑⠝_⠛⠗⠕⠥⠏=⠝⠑⠞.⠉⠉⠃⠇⠥⠑⠭
⠁⠗⠉⠓⠊⠧⠑⠎_⠃⠁⠎⠑_⠝⠁⠍⠑=⠇⠊⠟⠥⠊⠙⠃⠕⠥⠝⠉⠑
# ⠅⠕⠞⠇⠊⠝
# ⠓⠞⠞⠏⠎://⠅⠕⠞⠇⠊⠝⠇⠁⠝⠛.⠕⠗⠛/⠗⠑⠇⠑⠁⠎⠑⠎.⠓⠞⠍⠇
⠅⠕⠞⠇⠊⠝_⠧⠑⠗⠎⠊⠕⠝=2.1.10
# ⠓⠞⠞⠏⠎://⠍⠁⠧⠑⠝.⠋⠁⠃⠗⠊⠉⠍⠉.⠝⠑⠞/⠝⠑⠞/⠋⠁⠃⠗⠊⠉⠍⠉/⠋⠁⠃⠗⠊⠉-⠇⠁⠝⠛⠥⠁⠛⠑-⠅⠕⠞⠇⠊⠝/
⠋⠁⠃⠗⠊⠉_⠅⠕⠞⠇⠊⠝_⠧⠑⠗⠎⠊⠕⠝=1.13.1+⠅⠕⠞⠇⠊⠝.2.1.10
# ⠍⠉⠑⠋
⠍⠉⠑⠋_⠧⠑⠗⠎⠊⠕⠝=3.0.7-1.21.4
# ⠍⠉-⠁⠥⠞⠓⠇⠊⠃
⠍⠉_⠁⠥⠞⠓⠇⠊⠃_⠧⠑⠗⠎⠊⠕⠝=1.4.1
# ⠏⠕⠇⠽⠛⠇⠕⠞
⠏⠕⠇⠽⠛⠇⠕⠞_⠧⠑⠗⠎⠊⠕⠝=24.2.1
# ⠙⠚⠇
⠙⠚⠇_⠧⠑⠗⠎⠊⠕⠝=0.32.0
# ⠗⠑⠉⠕⠍⠍⠑⠝⠙⠑⠙ ⠍⠕⠙⠎
⠍⠕⠙_⠍⠑⠝⠥_⠧⠑⠗⠎⠊⠕⠝=13.0.2
⠎⠕⠙⠊⠥⠍_⠧⠑⠗⠎⠊⠕⠝=⠍⠉1.21.4-0.6.10-⠋⠁⠃⠗⠊⠉
⠇⠊⠞⠓⠊⠥⠍_⠧⠑⠗⠎⠊⠕⠝=⠍⠉1.21.4-0.14.8-⠋⠁⠃⠗⠊⠉
⠧⠊⠁⠋⠁⠃⠗⠊⠉⠏⠇⠥⠎_⠧⠑⠗⠎⠊⠕⠝=4.0.3
