/*
 * This file is part of LiquidBounce (https://github.com/CCBlueX/LiquidBounce)
 *
 * Copyright (c) 2015 - 2026 CCBlueX
 *
 * LiquidBounce is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LiquidBounce is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LiquidBounce. If not, see <https://www.gnu.org/licenses/>.
 */
package net.ccbluex.liquidbounce.features.item

import net.ccbluex.liquidbounce.LiquidBounce
import net.ccbluex.liquidbounce.features.command.commands.client.CommandContainers
import net.ccbluex.liquidbounce.utils.client.asPlainText
import net.ccbluex.liquidbounce.utils.client.mc
import net.ccbluex.liquidbounce.utils.text.PlainText
import net.minecraft.ChatFormatting
import net.minecraft.core.component.DataComponentPatch
import net.minecraft.core.component.DataComponents
import net.minecraft.network.chat.Component
import net.minecraft.world.SimpleContainer
import net.minecraft.world.item.component.ItemContainerContents
import net.minecraft.world.item.component.ItemLore

/**
 * Generates a list of [DataComponentPatch]s from a [SimpleContainer]
 *
 * These [DataComponentPatch]s can be used to recreate the inventory
 * using Minecraft Chests
 * by placing them together
 *
 * For example by typing this command:
 * give @p chest{display:{Name:"\"Hello!\""},BlockEntityTag:{Items:[{Slot:0,id:acacia_boat,Count:1}]}} 1
 *
 * This will give you a chest with the name "Hello!" and an acacia boat in the first slot
 * However, this will only work for the first 27 slots and not for the rest. This is why we split the
 *  inventory into multiple [DataComponentPatch]s
 *
 * There should also be [CommandContainers]
 * `.containers add <nbt>` which will give you the chest with the given nbt
 *
 * @return A list of [DataComponentPatch]s representing the inventory
 */
fun SimpleContainer.inventoryAsComponents(title: Component): List<DataComponentPatch> {
    val stacks = items

    // If the inventory is empty, we don't need to do anything
    if (stacks.isEmpty()) {
        return emptyList()
    }

    return stacks.chunked(27).mapIndexed { containerIndex, stacks ->
        val builder = DataComponentPatch.builder()

        builder.set(DataComponents.CUSTOM_NAME, title)
        builder.set(
            DataComponents.LORE, ItemLore(
                listOfNotNull(
                    "Container #$containerIndex".asPlainText(ChatFormatting.GOLD),
                    mc.currentServer?.let {
                        "Server: ${it.ip}".asPlainText(ChatFormatting.GOLD)
                    },
                    PlainText.EMPTY,
                    "Generated by ${LiquidBounce.CLIENT_NAME} ${LiquidBounce.clientVersion}"
                        .asPlainText(ChatFormatting.DARK_AQUA),
                    "Made with <3 by ${LiquidBounce.CLIENT_AUTHOR}"
                        .asPlainText(ChatFormatting.YELLOW),
                )
            )
        )
        builder.set(DataComponents.CONTAINER, ItemContainerContents.fromItems(stacks))

        builder.build()
    }
}

