/*
 * This file is part of LiquidBounce (https://github.com/CCBlueX/LiquidBounce)
 *
 * Copyright (c) 2015 - 2025 CCBlueX
 *
 * LiquidBounce is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LiquidBounce is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LiquidBounce. If not, see <https://www.gnu.org/licenses/>.
 */

package net.ccbluex.liquidbounce.ksp.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSClassDeclaration

internal fun KSClassDeclaration.normalizedQualifierName() =
    this.qualifiedName!!.asString().replace(".fun.", ".`fun`.")

internal inline fun CodeGenerator.writeObjectListFile(
    packageName: String,
    fileName: String,
    itemType: String,
    receiverName: String,
    extensionName: String,
    objects: Sequence<KSClassDeclaration>,
    mapper: (KSClassDeclaration) -> CharSequence = KSClassDeclaration::normalizedQualifierName,
//    extraContent: BufferedWriter.() -> Unit = {},
): Int {
    val listName = "list_" + itemType.hashCode().toUInt()
    var count = 0

    createNewFile(
        dependencies = Dependencies.ALL_FILES,
        packageName = packageName,
        fileName = fileName,
    ).bufferedWriter().use { writer ->
        writer
            .appendLine("// This file is generated by the KSP module.")
            .appendLine("@file:JvmName(\"generated-$fileName\")") // hide to Java
            .appendLine("package $packageName")
            .appendLine() // imports
            .appendLine("import java.util.Arrays")
            .appendLine("import java.util.Collections")
            .appendLine() // list
            .appendLine("private val $listName: List<$itemType> = Collections.unmodifiableList(")
            .appendLine("    Arrays.asList(")
            .apply {
                objects.forEach {
                    append("        ").append(mapper(it)).append(",\n")
                    count++
                }
            }
            .appendLine("    )")
            .appendLine(")")
            .appendLine()
            .appendLine("internal inline val $receiverName.$extensionName: List<$itemType>")
            .appendLine("    get() = $listName")
            .appendLine()

//        writer.extraContent()
    }

    return count
}
