build:
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

complexity:
  active: true
  NamedArguments:
    active: true
    threshold: 4
  ComplexCondition:
    threshold: 5
  LongParameterList:
    functionThreshold: 7
  CyclomaticComplexMethod:
    active: false
  CognitiveComplexMethod:
    active: true
    threshold: 16
  StringLiteralDuplication:
    active: false

performance:
  active: true
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: true
  ForEachOnRange:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
#  UnusedImports:
#    active: true
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 4
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    excludeGuardClauses: true
    max: 4
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 3
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  UnusedPrivateProperty:
    allowedNames: '_|ignored|expected|serialVersionUID|.+Handler\d*|repeatable'
  ForbiddenMethodCall:
    active: true
    methods:
      - 'kotlin.io.print'
      - 'kotlin.io.println'
      - 'java.math.BigDecimal.<init>(kotlin.Double)'
      - 'java.math.BigDecimal.<init>(kotlin.String)'
      - 'kotlin.system.measureTimeMillis'
      # glBindTexture: replace with GlStateManager._bindTexture(), because everything else will mess up the internal state handling.
      - 'org.lwjgl.opengl.GL11.glBindTexture'
      # Java stuffs
      - 'java.util.Vector.<init>()'
      - 'java.util.Stack.<init>()'
      - 'java.util.LinkedList.<init>()'
      - 'java.util.Hashtable.<init>()'
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
    multiLine: 'always'
