⠃⠥⠊⠇⠙:
  ⠑⠭⠉⠇⠥⠙⠑⠉⠕⠗⠗⠑⠉⠞⠁⠃⠇⠑: ⠋⠁⠇⠎⠑

⠉⠕⠝⠋⠊⠛:
  ⠧⠁⠇⠊⠙⠁⠞⠊⠕⠝: ⠞⠗⠥⠑
  ⠺⠁⠗⠝⠊⠝⠛⠎⠁⠎⠑⠗⠗⠕⠗⠎: ⠋⠁⠇⠎⠑
  ⠉⠓⠑⠉⠅⠑⠭⠓⠁⠥⠎⠞⠊⠧⠑⠝⠑⠎⠎: ⠋⠁⠇⠎⠑
  # ⠺⠓⠑⠝ ⠺⠗⠊⠞⠊⠝⠛ ⠕⠺⠝ ⠗⠥⠇⠑⠎ ⠺⠊⠞⠓ ⠝⠑⠺ ⠏⠗⠕⠏⠑⠗⠞⠊⠑⠎, ⠑⠭⠉⠇⠥⠙⠑ ⠞⠓⠑ ⠏⠗⠕⠏⠑⠗⠞⠽ ⠏⠁⠞⠓ ⠑.⠛.: '⠍⠽_⠗⠥⠇⠑_⠎⠑⠞,.*>.*>[⠍⠽_⠏⠗⠕⠏⠑⠗⠞⠽]'
  ⠑⠭⠉⠇⠥⠙⠑⠎: ''

⠉⠕⠍⠏⠇⠑⠭⠊⠞⠽:
  ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
  ⠝⠁⠍⠑⠙⠁⠗⠛⠥⠍⠑⠝⠞⠎:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
    ⠞⠓⠗⠑⠎⠓⠕⠇⠙: 4
  ⠉⠕⠍⠏⠇⠑⠭⠉⠕⠝⠙⠊⠞⠊⠕⠝:
    ⠞⠓⠗⠑⠎⠓⠕⠇⠙: 5
  ⠉⠽⠉⠇⠕⠍⠁⠞⠊⠉⠉⠕⠍⠏⠇⠑⠭⠍⠑⠞⠓⠕⠙:
    ⠁⠉⠞⠊⠧⠑: ⠋⠁⠇⠎⠑
  ⠉⠕⠛⠝⠊⠞⠊⠧⠑⠉⠕⠍⠏⠇⠑⠭⠍⠑⠞⠓⠕⠙:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
    ⠞⠓⠗⠑⠎⠓⠕⠇⠙: 16
  ⠎⠞⠗⠊⠝⠛⠇⠊⠞⠑⠗⠁⠇⠙⠥⠏⠇⠊⠉⠁⠞⠊⠕⠝:
    ⠁⠉⠞⠊⠧⠑: ⠋⠁⠇⠎⠑

⠏⠑⠗⠋⠕⠗⠍⠁⠝⠉⠑:
  ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
  ⠉⠕⠥⠇⠙⠃⠑⠎⠑⠟⠥⠑⠝⠉⠑:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
  ⠥⠝⠝⠑⠉⠑⠎⠎⠁⠗⠽⠏⠁⠗⠞⠕⠋⠃⠊⠝⠁⠗⠽⠑⠭⠏⠗⠑⠎⠎⠊⠕⠝:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑

⠑⠭⠉⠑⠏⠞⠊⠕⠝⠎:
  ⠞⠕⠕⠛⠑⠝⠑⠗⠊⠉⠑⠭⠉⠑⠏⠞⠊⠕⠝⠉⠁⠥⠛⠓⠞:
    ⠁⠉⠞⠊⠧⠑: ⠋⠁⠇⠎⠑

⠎⠞⠽⠇⠑:
  ⠍⠁⠛⠊⠉⠝⠥⠍⠃⠑⠗:
    ⠁⠉⠞⠊⠧⠑: ⠋⠁⠇⠎⠑
  ⠗⠑⠞⠥⠗⠝⠉⠕⠥⠝⠞:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
    ⠑⠭⠉⠇⠥⠙⠑⠛⠥⠁⠗⠙⠉⠇⠁⠥⠎⠑⠎: ⠞⠗⠥⠑
    ⠍⠁⠭: 4
  ⠇⠕⠕⠏⠺⠊⠞⠓⠞⠕⠕⠍⠁⠝⠽⠚⠥⠍⠏⠎⠞⠁⠞⠑⠍⠑⠝⠞⠎:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
    ⠍⠁⠭⠚⠥⠍⠏⠉⠕⠥⠝⠞: 3
  ⠺⠊⠇⠙⠉⠁⠗⠙⠊⠍⠏⠕⠗⠞:
    ⠁⠉⠞⠊⠧⠑: ⠋⠁⠇⠎⠑
  ⠋⠕⠗⠃⠊⠙⠙⠑⠝⠉⠕⠍⠍⠑⠝⠞:
    ⠁⠉⠞⠊⠧⠑: ⠋⠁⠇⠎⠑
  ⠥⠝⠥⠎⠑⠙⠏⠗⠊⠧⠁⠞⠑⠏⠗⠕⠏⠑⠗⠞⠽:
    ⠁⠇⠇⠕⠺⠑⠙⠝⠁⠍⠑⠎: '_|⠊⠛⠝⠕⠗⠑⠙|⠑⠭⠏⠑⠉⠞⠑⠙|⠎⠑⠗⠊⠁⠇⠧⠑⠗⠎⠊⠕⠝⠥⠊⠙|.+⠓⠁⠝⠙⠇⠑⠗\⠙*|⠗⠑⠏⠑⠁⠞⠁⠃⠇⠑'
  ⠋⠕⠗⠃⠊⠙⠙⠑⠝⠍⠑⠞⠓⠕⠙⠉⠁⠇⠇:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
    ⠍⠑⠞⠓⠕⠙⠎: [ '⠅⠕⠞⠇⠊⠝.⠊⠕.⠏⠗⠊⠝⠞', '⠅⠕⠞⠇⠊⠝.⠊⠕.⠏⠗⠊⠝⠞⠇⠝' ]
  ⠃⠗⠁⠉⠑⠎⠕⠝⠊⠋⠎⠞⠁⠞⠑⠍⠑⠝⠞⠎:
    ⠁⠉⠞⠊⠧⠑: ⠞⠗⠥⠑
    ⠎⠊⠝⠛⠇⠑⠇⠊⠝⠑: '⠝⠑⠧⠑⠗'
    ⠍⠥⠇⠞⠊⠇⠊⠝⠑: '⠁⠇⠺⠁⠽⠎'
