name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew 1.8.9-Forge:build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Nightly Build
        path: 1.8.9-Forge/build/libs/*.jar

    - name: Deploy LiquidBounce Nightly Build to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: ./1.8.9-Forge/build/libs/*.jar
